<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <title>C++: Exceptions Quiz</title>
    <meta name="author" content="Fred Swartz (www.leepoint.net/fred/)"/>
    <link rel="stylesheet" type="text/css" href="../notes.css"/>
    <script type="text/JavaScript" src="../notes.js"></script>
</head>
<body>
<h1><a href="../index.html">C++</a>: Exceptions Quiz</h1>

Name __________________________________

<br /><br />All answers are worth one point unless otherwise indicated. 



<h2>Exceptions</h2>
The following program uses try-throw-catch.
Note that if there is no catch for a type of exception, 
an error message like "abnormal program termination" is
printed and the program is terminated.

<pre class="example">
#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
using namespace std;

void f(int x);  // prototype

//=============================== main
int main() {
    int test;
    while (cin &gt;&gt; test) {
        try {
            cout &lt;&lt; "1 ";
            f(test);
            cout &lt;&lt; "2 ";
        }catch (out_of_range e) {
            cout &lt;&lt; "3 ";
            cout &lt;&lt; e.what();
            cout &lt;&lt; "4 ";
        }
        cout &lt;&lt; "5 " &lt;&lt; endl;
    }
    return 0;
}//end main


//=============================== f
void f(int x) {
    cout &lt;&lt; "6 ";
    if (x &lt; 0) {
        throw out_of_range("7 ");
    }else if (x &gt; 100) {
        throw length_error("8 ");
    }
    cout &lt;&lt; "9 ";
}//end f
</pre>

<ol type="1">
<li>(5 points) What is printed with input 1? _______________________________________
    </li>
<li>(5 points) What is printed with input -1? _______________________________________
    </li>
<li>(5 points) What is printed with input 1000? _______________________________________
    </li>
</ol>


  
<script type="text/JavaScript">footer("2001");</script>
</body>

</html>
